### ISSUE TITLE
Theme Testing: wd_s

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-gutenberg#11]
Do all the Gutenblocks work in wd_s? Do they look great out of the box and match our current wd_s styles? You may need to edit each blocks style.scss...

**WDS Gutenberg Blocks**

- [x] call-to-action
- [x] default
- [ ] github-gist
- [x] hero
- [ ] related-posts
- [x] two-column-block

**Default Gutenberg Blocks**

Offical list: https://github.com/WordPress/gutenberg/tree/master/blocks/library

- [x] audio
- [x] button
- [x] categories
- [x] code
- [x] columns
- [x] cover-image
- [x] embed
- [x] freeform - maybe removed?
- [x] gallery
- [x] heading
- [x] html
- [x] image
- [x] latest-posts
- [x] list
- [x] more
- [x] paragraph
- [x] preformatted
- [x] pullquote
- [x] quote
- [x] separator
- [x] shortcode
- [x] subhead
- [x] table
- [x] text-columns
- [x] verse
- [x] video

**Comment by ImBigWill** [comment]
It's actually separate from the task, so I might create a new one next week to ensure blocks in the admin mirror how they will appear on the front end. I did that work this afternoon at the plugin level. There's still a couple things to workout in terms of breakpoints in the editor etc. There's a common.scss but I'm not sure if we want to put globals there or break them out a little more like the front end which I can get started on next week when time permits.

New branch for editor styling:
wds-gutenberg/feature/editor-styles-to-match-front-end

**Comment by ImBigWill** [comment]
Continued working today on some backend styling mostly so it matches the front end. Updated our default block and any that had possible background options to go full width much like the hero. 

I also reorganized some global items into a sass folder and then imported them into the common.scss file so they're broken out and more manageable long term, not just one long file, as I'm sure more will come up along the way. 

Additionally added in some styles to increase the spacing between blocks on the backend, so when you hover/toggle open some toolbars they are still below the block above. When a block is hovered/selected/or being edited, it's now at full opacity, while the others will have significantly less while not being worked on.

### SCREENSHOT###
[Backend Block Opacity](https://www.dropbox.com/s/k26ypc1yq5d68rr/opacity-on-blocks.gif?raw=1)

**Comment by ImBigWill** [comment]
This should be up to date and was merged into the feature branch of wd_s in Feature/gutenberg this morning. I think we're ok to close this out and if further updates are needed we can update accordingly.

Reference: https://github.com/WebDevStudios/wd_s/commit/e95383779033a4fe0643b1812c6d8b8d92052f43
