### ISSUE TITLE
Add Deprecated Function for Existing Blocks

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-gutenberg#24]
After learning that once a block is saved, you can't go back and update the markup (without breaking the block)

Please convert all the `save` methods from JSX to a `render.php` file inside each respective block/component's directory.

- [x] call-to-action
- [x] default
- [x] github-gist
- [x] hero
- [x] related-posts
- [x] two-column-block

Setup a branch `feature/#24-block-save-to-render-php` for working.

**Edit:** After some more digging by @efuller, we realized that there is a not-so-well documented `deprecated` function for rendering in JSX which allows you to add new fields, adjust the output, etc. without breaking the block on the backend.  So that's nice!  Updated the task name and directive here to add that in where we're able (i.e., blocks rendering via JSX and not PHP).

**Comment by efuller** [comment]
I've added a page in the Wiki on block versioning! https://github.com/WebDevStudios/wds-gutenberg/wiki/Block-Versioning

I think we can wrap this issue tomorrow morning!
