### ISSUE TITLE
v1.0 Release Prep 🎉

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-gutenberg#43]
Wow, it's hard to believe we've made it to the end of Phase I. 

I believe that WebDevStudios is ready to work with our clients to provide them an amazing editing experience with [Gutenberg](https://github.com/WordPress/gutenberg), without having to rely on Advanced Custom Fields. That's not to say we're dropping support for ACF or our Content Blocks. The WDS Gutenberg project is just another tool in our tool-belt for providing the best possible solution for our clients.

Internally, we've changed the name of this project from "WDS Gutenberg" -> "WDS Blocks". This will require a rename of this repository, and a possible retrofit of any blog posts and documentation that exists. We're also dropping the ACF, MigrateDB Pro, and wd_s dev dependencies since Phase 1 was to recreate ACF content block functionality while testing our [starter theme](https://github.com/WebDevStudios/wd_s).

Here's my release prep to do list:

- [x] Rename repository
- [x] Remove install/update script
- [x] Remove ACF/MDB Pro/wd_s dependencies from readme
- [x] Rewrite readme to reflect updated development workflow
- [x] Add basic usage workflow to readme
- [x] Ensure branding and description is consistent 
- [x] Ensure block names and icons are consistent with WDS branding
- [x] Wiki and documentation are on point
- [ ] Launch blog post
- [x] Tag and release v1.0

For Phase II we're going to focus on polish, enhanced accessibility, and adding more blocks! Also, we'll be testing against the [.org version of Gutenberg](https://wordpress.org/plugins/gutenberg/), since the [Github version](https://github.com/WordPress/gutenberg) has proven to be incredible weird in regards to already-built-blocks.

Thank you to @coreymcollins @kellenmace @jomurgel @efuller @ImBigWill for [their contributions](https://github.com/WebDevStudios/wds-gutenberg/graphs/contributors)!

**Comment by coreymcollins** [comment]
Everything should be renamed at this point - documentation #5 is waiting on `MultiSelect` being added by @efuller, then could probably use a review by a dev (perhaps one not super familiar with the project) to make sure everything is covered.
